//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Thesis
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Annotation { get; set; }
        public int ProfessorId { get; set; }
    
        public virtual Professor Professor { get; set; }
    }
}
